# Generated by Django 4.0.1 on 2022-01-07 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('startDate', models.DateTimeField(default=datetime.datetime.now)),
                ('endDate', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('description', models.TextField(blank=True, default='', max_length=5000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
                'ordering': ('-startDate',),
            },
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TypeVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalDate', models.DateTimeField(default=datetime.datetime.now)),
                ('fullName', models.CharField(max_length=200, verbose_name='fullName')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='performance')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typevisitor', verbose_name='type')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitor',
                'ordering': ('-arrivalDate',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeevent', verbose_name='type'),
        ),
    ]
