# Generated by Django 4.0.1 on 2022-01-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeevent',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typevisitor',
            old_name='Name',
            new_name='name',
        ),
    ]
